[package]
name = "tsgo-rust-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
rmp = "0.8.14"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = { version = "0.26", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
rstest = "0.25.0"
similar-asserts = "1.6"

[profile.dev.package]
similar.opt-level = 3
