[package]
name = "tsgo-vfs"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Virtual file system abstraction for tsgo integration"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
dynosaur = { workspace = true }
trait-variant = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { version = "1.45.1", features = ["full"] } 