[package]
name = "tsgo-syntax"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "TypeScript syntax kind definitions for tsgo-rust-ipc"

[dependencies]
strum = { workspace = true } 
