[package]
name = "tsgo-syntax"
description = "TypeScript syntax kind definitions for tsgo-rust-ipc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
strum = { workspace = true } 
